ID_DO_PRODUTO = 0
NOME = 1
QTD = 2
PRECO = 3

ABRIR_CAIXA = 1
NAO_ABRIR_CAIXA = 2
ATENDER_CLIENTE = 1
FECHAR_CAIXA = 2
INICIAR_ATENDIMENTO = 1
NAO_INICIAR_ATENDIMENTO = 2
FINALIZAR_ATENDIMENTO = 1
NAO_FINALIZAR_ATENDIMENTO = 2