ABRIR_CAIXA = 1
NAO_ABRIR_CAIXA = 2
ATENDER_CLIENTE = 1
FECHAR_CAIXA = 2
INICIAR_ATENDIMENTO = 1
NAO_INICIAR_ATENDIMENTO = 2
FINALIZAR_ATENDIMENTO = 1
NAO_FINALIZAR_ATENDIMENTO = 2

MENU_SIG_CLIENTES = 1
MENU_SIG_PRODUTOS = 2
MENU_SIG_SAIR = 3

MENU_CLIENTES_COMPRAS = 1
MENU_CLIENTES_SEM_COMPRAS = 2
MENU_CLIENTES_VOLTAR = 3

MENU_CLIENTES_CONSULTAR_COMPRAS = 1
MENU_CLIENTES_MAIS_COMPRAM = 2
MENU_CLIENTES_MAIS_GASTAM = 3
MENU_CLIENTES_COMPRAS_VOLTAR = 4

MENU_PRODUTOS_LISTAR = 1
MENU_PRODUTOS_CADASTRAR = 2
MENU_PRODUTOS_ALTERAR = 3
MENU_PRODUTOS_REMOVER = 4
MENU_PRODUTOS_CONSULTAS = 5
MENU_PRODUTOS_VOLTAR = 6

MENU_CONSULTA_MAIS_VENDIDOS = 1
MENU_CONSULTA_MENOS_VENDIDOS = 2
MENU_CONSULTA_POUCO_ESTOQUE = 3
MENU_CONSULTA_FORNECEDORES = 4
MENU_CONSULTA_VOLTAR = 5